### ISSUE TITLE
js-flot fails to build

### ISSUE THREAD

**Issue by kozross** [ndmitchell/js-flot#3]
I tried to use ``cabal new-install`` to get ``hoogle``. However, when I tried that, I got this:

```
# bunch of packages build
Failed to build js-flot-0.8.3. The failure occurred during the configure step.
Build log (
/home/koz/.cabal/logs/ghc-8.6.5/js-flot-0.8.3-5d291987ea55095b1e71e335fbe7d8c186ce1b91bc2ca8bcd56fd08e6a879f7f.log
):
Configuring library for js-flot-0.8.3..
cabal: ghc-pkg dump failed: dieVerbatim: user error (cabal:
'/home/koz/ghc-86/bin/ghc-pkg' exited with an error:
ghc-pkg: internal error: evacuate: stack frame at 0x4201dca540

(GHC version 8.6.5 for x86_64_unknown_linux)
Please report this as a GHC bug: http://www.haskell.org/ghc/reportabug
)

cabal: Failed to build js-flot-0.8.3 (which is required by exe:hoogle from
hoogle-5.0.17.11). See the build log above for details.
```

Is this a package issue, or is something really wrong on my machine? ``cabal --version`` reports ``3.0.0.0``.

**Comment by kozross** [comment]
OK, this is strange. I tried running ``cabal new-install`` again, and everything worked correctly....

**Comment by ndmitchell** [comment]
That issue is super scary, but I don't think it's due to this library. I'd guess at buggy GHC binaries? Where did you get them from?

**Comment by kozross** [comment]
From [the GHC website download page][1]. Weirdly, I have never seen this before, and not since either.

[1]: https://www.haskell.org/ghc/download_ghc_8_6_5.html#linux_x86_64

**Comment by ndmitchell** [comment]
Nothing much to be done then. If you can get it to recur regularly I suggest a GHC but.
