### ISSUE TITLE
Upgrade to flot 4.2.1?

### ISSUE THREAD

**Issue by jonascarpay** [ndmitchell/js-flot#4]
There's [some dicussion over on criterion](https://github.com/bos/criterion/issues/213#issuecomment-717352722) about the log-axis support in newer versions of flot. How would you feel about updating js-flot to a newer version? I'd be happy to make a PR for it here and fix up criterion, but it would mean somebody would need to update hoogle and shake.

**Comment by ndmitchell** [comment]
Please do! PR very welcome. I'll take care of Hoogle and Shake if they need it.

**Comment by RyanGlScott** [comment]
Out of curiosity, do you have a sense for how significant the breaking changes between 0.8.3 (the current version used in `js-flot`) and 4.2.1 would be? Interestingly, the [`flot` changelog](https://github.com/flot/flot/blob/b6ca777f75d0750201c91b12ebc1c914d0e2cc12/CHANGELOG.md#changelog) itself doesn't even have an entry for anything beyond 3.2.0, so I'm somewhat unclear on what would break.

**Comment by ndmitchell** [comment]
No idea - I was tracking the Flot changes via an RSS subscription to their blog. Either they moved their blog or stopped updating it, so I wasn't aware we'd fallen behind.

**Comment by jonascarpay** [comment]
Closing this, see https://github.com/ndmitchell/js-flot/pull/5
